name: Backport merged pull request
on:
  pull_request_target:
    types: [closed, labeled]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  inspect:
    name: Inspec PR to find backport labels
    if: github.event.pull_request.merged && (((github.event.action == 'closed') || ((github.event.action == 'labeled') && startsWith(github.event.label.name, 'backport/'))))
    outputs:
      target-branches: ${{ steps.target-branches.outputs.target-branches }}
    steps:
      - name: Test
        id: target-branches
        run: echo "release/v2.0.0" > $GITHUB_OUTPUT
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    needs: inspect
    strategy:
      matrix:
        target-branch: ${{ fromJSON(needs.inspect.outputs.target-branches) }}
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v4
        with:
          label_pattern:
          target_branches: ${{ matrix.target-branch }}
          branch_name: backport/${pull_number}/-/${target_branch}
          copy_assignees: true
          copy_requested_reviewers: true
          git_committer_name: backport-bot
          git_committer_email: backport-bot@ebu.ch
          pull_description: 'Backport of #${pull_number} to `${target_branch}`.'
          pull_title: '[Backport to ${target_branch}] ${pull_title}'
          add_labels: 'backport,automation'
